/**
 * Public exports for game state management.
 * Import from '@/lib/game/state' to access state factory, queries, and mutations.
 */

// Factory
export {
  calculatePlayerPositions,
  calculateStormOrder,
  createGameState,
  getDefaultPlayerPositions,
  shuffle,
  type CreateGameOptions,
} from "./factory";

// Queries
export {
  areAllied,
  areSectorsSeparatedByStorm,
  canFactionBid,
  canReviveLeader,
  canShipToTerritory,
  checkStrongholdVictory,
  getAlly,
  getAvailableLeaders,
  getAvailableLeadersForCapture,
  getBGAdvisorsInTerritory,
  getBGFightersInSector,
  getBGFightersInTerritory,
  getCapturedLeaders,
  getControlledStrongholds,
  getDefenseCards,
  getFactionAtPosition,
  getFactionHandSize,
  getFactionMaxHandSize,
  getFactionSpice,
  getFactionState,
  getFactionsInTerritory,
  getFactionsInTerritoryAndSector,
  getFactionsOccupyingTerritory,
  getFirstPlayer,
  getForceCountInTerritory,
  getForcesInTanks,
  getForcesInTerritory,
  getLeadersInTanks,
  getNextInStormOrder,
  getOccupiedStrongholds,
  getPlayerPosition,
  getPlayerPositions,
  getProtectedLeaders,
  getPublicFactionState,
  getReserveForceCount,
  getSpiceInTerritory,
  getStrongholdOccupancy,
  getTargetFactionForLeaderKill,
  getTotalForcesOnBoard,
  getWeaponCards,
  hasAvailableLeaders,
  hasActiveKaramaInterrupt,
  hasCheapHero,
  hasKaramaCard,
  isEarlierInStormOrder,
  isLeaderProtectedOnBoard,
  isSectorInStorm,
  isTerritoryInStorm,
  shouldTriggerPrisonBreak,
  validateHandSize,
  validateStrongholdOccupancy,
  allKaramaResponsesReceived,
  getKaramaInterruptor,
} from "./queries";

// Mutations
export {
  addDeal,
  addSpice,
  addSpiceToTerritory,
  advancePhase,
  advanceTurn,
  breakAlliance,
  captureLeader,
  convertBGAdvisorsToFighters,
  convertBGFightersToAdvisors,
  destroySpiceInTerritory,
  discardTreacheryCard,
  drawTreacheryCard,
  formAlliance,
  killCapturedLeader,
  killKwisatzHaderach,
  killLeader,
  logAction,
  markKwisatzHaderachUsed,
  markLeaderUsed,
  moveForces,
  moveStorm,
  recordWinAttempt,
  removeDeal,
  removeSpice,
  removeSpiceFromTerritory,
  removeTraitorCard,
  resetKwisatzHaderachTurnState,
  resetLeaderTurnState,
  returnAllCapturedLeaders,
  returnCapturedLeader,
  returnLeaderToPool,
  reviveForces,
  reviveKwisatzHaderach,
  reviveLeader,
  sendForcesToReserves,
  sendForcesToTanks,
  shipForces,
  setActiveFactions,
  transferSpice,
  updateKwisatzHaderach,
  updateStormOrder,
} from "./mutations";

// Force utilities
export {
  addToForceCount,
  addToStack,
  calculateLossDistribution,
  convertAdvisorsToFighters,
  convertFightersToAdvisors,
  createForceStack,
  emptyForceCount,
  findStack,
  findStacksInTerritory,
  getForcesAt,
  getTotalForces,
  isForceCountEmpty,
  isStackEmpty,
  mergeForceCount,
  moveStackForces,
  removeEmptyStacks,
  removeFromStack,
  subtractFromForceCount,
  totalForcesOnBoard,
  updateStackForces,
} from "./force-utils";
